import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {fixture,fixtureHTML} from './fixture';import {parseVehicle,parsePrice,parseMileage,parseStock,parseVin} from '../lib/parser';import {parseSearch,search} from '../lib/search';import {jsonFeed,csvFeed,structuredData,sitemapEntries} from '../lib/feed';import {sourceFrom,adminToken,validAdmin,rateLimit,sameOrigin} from '../lib/security';import {authorizedURL} from '../lib/source-http';
process.env.DATABASE_PATH=join(mkdtempSync(join(tmpdir(),'gateway-unit-')),'test.sqlite');
const {db,vehicles,vehicle,applyInventory,saveInquiry}=await import('../lib/db');
test('vehicle parser reads source structured facts',()=>{const v=parseVehicle(fixtureHTML(),'https://ultimatemotor.ca/vehicle/test-only-fixture');assert.ok(v);assert.equal(v.stock_number,'TEST-ONLY-001');assert.equal(v.vin,'JH4KA8260MC000001');assert.equal(v.model,'RAV4');assert.equal(v.price_cad,32000);assert.equal(v.mileage_km,75000);assert.equal(v.availability,'available');assert.equal(v.accident_status,null);});
test('price parser rejects finance, missing, negative and malformed prices',()=>{for(const x of ['Call for price','$150 bi-weekly',null,'Unknown','-100','12.3.4','Only 30000'])assert.equal(parsePrice(x),null);assert.equal(parsePrice('$32,999 CAD'),32999);assert.equal(parsePrice(0),0);});
test('mileage parser handles km without silently treating miles as km',()=>{assert.equal(parseMileage('80,000 km'),80000);assert.equal(parseMileage('10,000 miles'),null);assert.equal(parseMileage('Unknown'),null);});
test('stock/VIN parsing validates VIN characters',()=>{assert.equal(parseStock('Stock #: A-123'),'A-123');assert.equal(parseVin('VIN: JH4KA8260MC000001'),'JH4KA8260MC000001');assert.equal(parseVin('INVALIDVIN1234567'),null);});
test('parser leaves absent fields unknown',()=>{const v=parseVehicle('<h1>2022 Toyota RAV4</h1><main>Stock #: TEST-ONLY-002</main>','https://ultimatemotor.ca/vehicle/test-only-2');assert.ok(v);assert.equal(v.price_cad,null);assert.equal(v.model,null);assert.equal(v.availability,'unknown');assert.equal(v.accident_status,null);});
test('parser rejects listing and unrelated product pages',()=>{assert.equal(parseVehicle('<h1>Inventory</h1>','https://ultimatemotor.ca/inventory'),null);const s={'@type':'Product',name:'Oil filter',sku:'OIL'};assert.equal(parseVehicle(`<script type="application/ld+json">${JSON.stringify(s)}</script>`,'https://ultimatemotor.ca/accessories'),null);});
test('parser reads table specifications and explicit availability',()=>{const v=parseVehicle('<h1>2022 Toyota RAV4</h1><main><table><tr><td>Stock #</td><td>TEST-ONLY-003</td></tr><tr><td>Model</td><td>RAV4</td></tr><tr><td>Price CAD</td><td>$30,000 CAD</td></tr><tr><td>Mileage</td><td>90,000 km</td></tr><tr><td>Status</td><td>Available</td></tr></table></main>','https://ultimatemotor.ca/vehicle/test-only-3');assert.ok(v);assert.equal(v.model,'RAV4');assert.equal(v.mileage_km,90000);assert.equal(v.price_cad,30000);assert.equal(v.availability,'available');});
test('non-CAD price is not advertised as CAD',()=>{const v=parseVehicle(fixtureHTML().replace('"CAD"','"USD"'),'https://ultimatemotor.ca/vehicle/test-only-fixture');assert.equal(v?.price_cad,null);});
test('unsafe image URLs are discarded',()=>{const html=fixtureHTML().replace('"model":"RAV4"','"image":"javascript:alert(1)","model":"RAV4"');assert.equal(parseVehicle(html,'https://ultimatemotor.ca/vehicle/test-only-fixture')?.primary_image,null);});
test('search parses year, model, trim, drive, budget and mileage',()=>{assert.deepEqual(parseSearch('2022 RAV4 XLE AWD under 35000 and under 80000 km'),{year:2022,drivetrain:'awd',maxPrice:35000,maxMileage:80000,terms:['rav4','xle']});assert.equal(parseSearch('2022+ rav4 under $35k').minYear,2022);});
test('requested searches return actual supplied inventory or labeled closest results',()=>{const list=[fixture(),fixture({id:'test-only-honda',make:'Honda',model:'Civic',price_cad:25000,body_style:'Sedan',drivetrain:'FWD'})];for(const q of ['2022 rav4','rav4 under 35000','awd suv','honda under 30000']){const r=search(list,q);assert.equal(r.exact,true);assert.ok(r.results.length);assert.ok(r.results.every(v=>list.includes(v)));}assert.equal(search(list,'ferrari under 1000').exact,false);});
test('unknown price and mileage cannot satisfy numeric constraints',()=>{const unknown=fixture({price_cad:null,mileage_km:null});assert.equal(search([unknown],'under 35000').exact,false);assert.equal(search([unknown],'under 80000 km').exact,false);});
test('JSON feed includes only available inventory and source URLs',()=>{const feed=jsonFeed([fixture(),fixture({id:'test-sold',availability:'sold'})]);assert.equal(feed.vehicles.length,1);assert.equal(feed.vehicles[0].source_vehicle_url,fixture().source_vehicle_url);assert.ok(feed.vehicles[0].vehicle_url.includes('/v/test-only-001'));});
test('CSV quotes fields, retains zero, and mitigates spreadsheet formulas',()=>{const csv=csvFeed([fixture({stock_number:'=SUM(1,2)',price_cad:0})]);assert.ok(csv.includes(`"'=SUM(1,2)"`));assert.ok(csv.includes('"0"'));assert.equal(csv.split('\r\n').length,2);});
test('vehicle structured data parses and omits nonexistent accident facts',()=>{const s=JSON.parse(JSON.stringify(structuredData(fixture())));assert.deepEqual(s['@type'],['Car','Product']);assert.equal(s.offers.priceCurrency,'CAD');assert.equal(s.offers.availability,'https://schema.org/InStock');assert.equal(s.mileageFromOdometer.unitCode,'KMT');assert.equal(s.offers.seller.name,'Ultimate Motors');assert.equal(s.accidentHistory,undefined);assert.equal(structuredData(fixture({availability:'unknown'})).offers,undefined);});
test('sitemap includes available VDPs, excludes missing and sold',()=>{const entries=sitemapEntries([fixture(),fixture({id:'sold-only',availability:'sold'}),fixture({id:'missing-only',availability:'missing'})]);assert.equal(entries.length,3);assert.ok(entries[2].url.endsWith('/v/test-only-001'));});
test('inventory add/update preserves last_seen and updates changed facts',()=>{db.exec('DELETE FROM vehicles');applyInventory([fixture()],true);const old=vehicle('test-only-001')!;assert.ok(old.last_seen_at);applyInventory([fixture({price_cad:31000,mileage_km:75100})],true);assert.equal(vehicle('test-only-001')?.price_cad,31000);assert.equal(vehicle('test-only-001')?.mileage_km,75100);});
test('inquiry save records anonymous vehicle/source/question/timestamp',()=>{const id=saveInquiry({session_id:'test-session',vehicle_id:'test-only-001',source:'chatgpt',question:'Has this vehicle been in an accident?'});const row=db.prepare('SELECT * FROM inquiries WHERE inquiry_id=?').get(id);assert.equal(row?.source,'chatgpt');assert.equal(row?.vehicle_id,'test-only-001');assert.ok(row?.created_at);assert.equal(row?.contact_value,null);});
test('inquiry validation rejects unknown vehicle and unconsented contact',()=>{assert.throws(()=>saveInquiry({session_id:'s',vehicle_id:'invalid',source:'direct',question:'hi'}));assert.throws(()=>saveInquiry({session_id:'s',vehicle_id:null,source:'direct',question:'hi',contact_value:'a@example.com'}));});
test('partial and failed sync cannot remove inventory',()=>{db.exec('DELETE FROM vehicles');applyInventory([fixture(),fixture({id:'test-only-002',stock_number:'TEST-ONLY-002'})],true);applyInventory([fixture()],false);assert.equal(vehicle('test-only-002')?.availability,'available');assert.throws(()=>applyInventory([],true));assert.equal(vehicles().length,2);assert.equal(vehicle('test-only-002')?.availability,'available');});
test('three complete missing observations mark unavailable and reappearance restores',()=>{applyInventory([fixture()],true);assert.equal(vehicle('test-only-002')?.availability,'missing');applyInventory([fixture()],true);assert.equal(vehicle('test-only-002')?.availability,'missing');applyInventory([fixture()],true);assert.equal(vehicle('test-only-002')?.availability,'unavailable');applyInventory([fixture(),fixture({id:'test-only-002',stock_number:'TEST-ONLY-002'})],true);assert.equal(vehicle('test-only-002')?.availability,'available');});
test('missing evidence set protects inventory omitted by discovery',()=>{applyInventory([fixture()],true,new Set());assert.equal(vehicle('test-only-002')?.availability,'available');applyInventory([fixture()],true,new Set(['test-only-002']));assert.equal(vehicle('test-only-002')?.availability,'missing');});
test('sync failure logs error and keeps previously valid database',async()=>{const {syncInventory}=await import('../lib/sync');process.env.SOURCE_BASE_URL='https://unauthorized.example';await assert.rejects(syncInventory(),/authorized source/);assert.equal(vehicles().length,2);assert.equal(db.prepare('SELECT status FROM sync_runs ORDER BY id DESC LIMIT 1').get()?.status,'failed');delete process.env.SOURCE_BASE_URL;});
test('source HTTP accepts only authorized HTTPS hosts',()=>{assert.equal(authorizedURL('https://ultimatemotor.ca/inventory'),true);for(const url of ['http://ultimatemotor.ca','https://evil.example','https://ultimatemotor.ca.evil.example','https://user:pass@ultimatemotor.ca','https://ultimatemotor.ca:444'])assert.equal(authorizedURL(url),false);});
test('tracking recognizes explicit UTM and trusted referrer hostname',()=>{assert.equal(sourceFrom(new URL('https://gateway.example/?utm_source=chatgpt')),'chatgpt');assert.equal(sourceFrom(new URL('https://gateway.example/'),'https://www.google.ca/search?q=a'),'google');assert.equal(sourceFrom(new URL('https://gateway.example/'),'https://evil-google.com'),'unknown');assert.equal(sourceFrom(new URL('https://gateway.example/')),'direct');});
test('admin disabled without password; tampering and expiry fail',()=>{delete process.env.ADMIN_PASSWORD;assert.equal(validAdmin(adminToken(Date.now()+10000)),false);process.env.ADMIN_PASSWORD='unit-test-only-password';const token=adminToken(Date.now()+10000);assert.equal(validAdmin(token),true);assert.equal(validAdmin(token+'x'),false);assert.equal(validAdmin(adminToken(Date.now()-1)),false);delete process.env.ADMIN_PASSWORD;});
test('rate limit and same-origin check block abuse',()=>{assert.equal(rateLimit('unit-rate',1),true);assert.equal(rateLimit('unit-rate',1),false);assert.equal(sameOrigin(new Request('https://gateway.example/api/inquiries',{headers:{origin:'https://evil.example'}})),false);assert.equal(sameOrigin(new Request('https://gateway.example/api/inquiries',{headers:{origin:'https://gateway.example'}})),true);});

test('public Zop adapter maps visible facts and nullable history',async()=>{const {parsePublicDocument}=await import('../lib/zop');const c={IMAGE_DOMAIN:'https://zopsoftware-asset.b-cdn.net',COLLECTION:'d97eed1656fc63b97ee811051024f475',API_KEY:'synthetic-test-key',TYPESENSE_HOST:'v6eba1srpfohj89dp-1.a1.typesense.net'};const d={inventory_id:1,stock_no:'TEST-ONLY-ZOP',vin:'JH4KA8260MC000001',vindisplay:'1',year:2022,make:'Toyota',model:'RAV4',trim:'XLE',price:32000,selling_price:32000,hide_price:0,special_price_on:0,odometer:75000,km_miles:'KM',status:'Instock',visibility:1,deleted_at:0,page_url:'/inventory/test-only-fixture/1/',image_urls:'/test-image.jpg; /test-image-2.jpg',vehicle_description:'<p>Synthetic <strong>fixture</strong></p>',drivetrain:'All-Wheel Drive'};const v=parsePublicDocument(d,c);assert.equal(v.price_cad,32000);assert.equal(v.mileage_km,75000);assert.equal(v.vin,d.vin);assert.equal(v.description,'Synthetic fixture');assert.equal(v.image_urls.length,2);assert.equal(v.accident_status,null);assert.equal(parsePublicDocument({...d,hide_price:1,vindisplay:'0'},c).price_cad,null);assert.equal(parsePublicDocument({...d,vindisplay:'0'},c).vin,null);assert.equal(parsePublicDocument({...d,km_miles:'MI'},c).mileage_km,null);assert.throws(()=>parsePublicDocument({...d,status:'Sold'},c));assert.throws(()=>parsePublicDocument({...d,page_url:'https://evil.example'},c));});
test('drivetrain aliases from real source vocabulary match AWD searches',()=>{assert.equal(search([fixture({drivetrain:'All-Wheel Drive'})],'awd suv').exact,true);const s=structuredData(fixture({drivetrain:'All-Wheel Drive'}));assert.equal(s.driveWheelConfiguration,'https://schema.org/AllWheelDriveConfiguration');});
test('published search configuration is parsed as data, never evaluated',async()=>{const {publishedSearchConfig}=await import('../lib/zop');assert.equal(publishedSearchConfig('<html>No config</html>'),null);assert.throws(()=>publishedSearchConfig('function globalZDProperties() { return {"TYPESENSE_HOST":"evil.example","IMAGE_DOMAIN":"https://evil.example","COLLECTION":"abc","API_KEY":"test"} }'));});

test('same-origin validation honors the actual HTTP host through Next binding',()=>{assert.equal(sameOrigin(new Request('http://0.0.0.0:3000/api/inquiries',{headers:{host:'localhost:3000',origin:'http://localhost:3000'}})),true);assert.equal(sameOrigin(new Request('http://0.0.0.0:3000/api/inquiries',{headers:{host:'localhost:3000',origin:'http://evil.example'}})),false);});
test('JSON-LD serializer prevents closing script injection and preserves JSON data',async()=>{const {serializeJsonLd}=await import('../lib/feed');const input={name:'</script><script>alert(1)</script>'};const value=serializeJsonLd(input);assert.equal(value.includes('<'),false);assert.deepEqual(JSON.parse(value),input);});

test('request decoder rejects oversized and non-JSON bodies',async()=>{const {readJSON}=await import('../lib/request');await assert.rejects(readJSON(new Request('https://gateway.example',{method:'POST',headers:{'Content-Type':'application/json'},body:'x'.repeat(10001)})),/too large/);await assert.rejects(readJSON(new Request('https://gateway.example',{method:'POST',headers:{'Content-Type':'text/plain'},body:'{}'})),/content type/);await assert.rejects(readJSON(new Request('https://gateway.example',{method:'POST',headers:{'Content-Type':'application/json'},body:'not-json'})),/Invalid JSON/);assert.deepEqual(await readJSON(new Request('https://gateway.example',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"question":"test"}'})),{question:'test'});});

test('search normalizes source body style vocabulary and does not mistake five-digit budget for year',()=>{assert.equal(search([fixture({body_style:'Sport Utility Vehicle',drivetrain:'All-Wheel Drive'})],'awd suv').exact,true);const parsed=parseSearch('honda under 20220');assert.equal(parsed.year,undefined);assert.equal(parsed.maxPrice,20220);});

test('source attribution rejects spoofed Google domains and recognizes Copilot',()=>{assert.equal(sourceFrom(new URL('https://gateway.example/'),'https://google.evil.example/search'),'unknown');assert.equal(sourceFrom(new URL('https://gateway.example/'),'https://copilot.microsoft.com/'),'copilot');assert.equal(sourceFrom(new URL('https://gateway.example/'),'https://chat.openai.com/'),'chatgpt');});
