import {vehicles} from '@/lib/db';import {title,base} from '@/lib/model';import {budgetEstimate,maximumListingPrice,budgetMoney} from '@/lib/budget';
export const dynamic='force-dynamic';
export function generateMetadata(){return {title:'Ontario car budget calculator · 安省买车预算 | Warren Vehicle Finder',description:'Calculate an Ontario dealer purchase HST illustration and a maximum listing-price budget. Check certification and fees before you buy.',alternates:{canonical:base()+'/budget'}};}
export default async function Budget({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const p=await searchParams;const amount=(key:string,fallback:number)=>{const raw=p[key];if(typeof raw!=='string'||!raw.trim())return fallback;const n=Number(raw);return Number.isFinite(n)&&n>=0&&n<=1_000_000?n:fallback;};
 const price=amount('price',9299),optional=amount('optional',0),licensing=amount('licensing',0),budget=amount('budget',12000);
 const estimate=budgetEstimate(price,optional,licensing),maximum=maximumListingPrice(budget,optional,licensing);
 const matches=vehicles(true).filter(v=>v.price_cad!==null&&v.price_cad<=maximum).sort((a,b)=>a.price_cad!-b.price_cad!).slice(0,5);
 const question=`Ontario dealer purchase budget comparison\nTotal budget: CAD ${budget}\nListing price: CAD ${price}\nOptional taxable cost entered: CAD ${optional}\nLicensing reserve entered: CAD ${licensing}\nHST illustration: CAD ${estimate.tax}\nKnown-input subtotal: CAD ${estimate.total}\nCity / 城市:\nUse / 用途:\nBuying timeframe / 购买时间:\nPublic listing links (up to 3) / 公开车源链接:\nMy question / 我的问题:`;
 return <><p className="muted">FREE PLANNING TOOL · 免费预算工具</p><h1>What does that car price mean for your budget?<br/><span lang="zh">标价以外，你的买车预算还差多少？</span></h1><p>An Ontario dealer-purchase illustration with 13% HST. No login, phone number or email needed to use this calculator.</p><p lang="zh">按安省车行购车、13% HST 计算示例，无需注册或留下联系方式。结果不是卖家报价，也不包含保险、融资利息、维修或未确认费用。</p>
 <div className="grid"><section className="panel"><h2>Your numbers / 输入金额</h2><form action="/budget" method="get"><label>Total purchase budget / 总购车预算（CAD）<input type="number" name="budget" min="0" max="1000000" step="0.01" required defaultValue={budget}/></label><label>Advertised listing price / 页面标价（CAD）<input type="number" name="price" min="0" max="1000000" step="0.01" required defaultValue={price}/></label><label>Optional taxable item not already included / 自选且未含在标价中的应税项目<input type="number" name="optional" min="0" max="1000000" step="0.01" required defaultValue={optional}/></label><p className="muted">Default $0. Only enter a genuinely optional item you intend to buy, after checking it is not already included. This is not an allowance for hidden mandatory dealer fees. / 默认0，不重复计费；不能把隐藏的强制车行费当作合理附加费。</p><label>Licensing reserve / 牌照注册预留金额<input type="number" name="licensing" min="0" max="1000000" step="0.01" required defaultValue={licensing}/></label><p className="muted">Enter a confirmed amount or your own reserve. $0 means no amount included, not that licensing is free.</p><button>Calculate / 计算</button></form></section>
 <section className="panel" aria-live="polite"><h2>Known-input illustration / 已知输入示例</h2><dl><dt>Advertised price / 标价</dt><dd>{budgetMoney(price)}</dd><dt>Optional item / 自选项目</dt><dd>{budgetMoney(optional)}</dd><dt>13% HST illustration</dt><dd>{budgetMoney(estimate.tax)}</dd><dt>Licensing reserve / 预留</dt><dd>{budgetMoney(licensing)}</dd><dt>Known-input subtotal / 输入项小计</dt><dd className="price">{budgetMoney(estimate.total)}</dd><dt>Within your entered budget? / 是否超出输入预算？</dt><dd>{estimate.total<=budget?'Yes, for these inputs only / 仅这些输入项未超预算':'No / 已超预算'}</dd></dl><p className="notice">Not an out-the-door quote. A $0 fee field means excluded or unknown. Private sales, trade-ins, financing, luxury tax and other tax exceptions require separate treatment. / 不是落地价；私人交易、置换、贷款及特殊税务不能套用本工具。</p><h2>Work backward / 反推标价预算</h2><p>At your entered budget of {budgetMoney(budget)}, the maximum listing-price allowance is <strong>{budgetMoney(maximum)}</strong> for these assumptions.</p><a className="button" href={'/ask?source=budget_tool&question='+encodeURIComponent(question)}>Ask about my budget / 提交预算问题</a><p className="muted">Contact details are optional. A reply requires your contact consent. No reply deadline, seller response or buying outcome is guaranteed.</p></section></div>
 <h2>Listings to investigate / 可进一步核实的车源</h2><p>One public source, not the whole GTA market. These prices fit only the calculation inputs above; certification and other unknowns may change the actual budget. Availability and price must be confirmed with the seller.</p>{matches.length?<div className="grid">{matches.map(v=><div className="panel" key={v.id}><h3><a href={'/v/'+encodeURIComponent(v.id)}>{title(v)}</a></h3><p>Source-listed price: {budgetMoney(v.price_cad!)}</p><p>Price + 13% HST only: {budgetMoney(budgetEstimate(v.price_cad!).total)}</p><p className="muted">Not a certified or final-price claim. Source observed {new Date(v.last_seen_at).toISOString().slice(0,10)}.</p></div>)}</div>:<p className="notice">No current source listings fit these inputs. We will not invent a match or substitute a more expensive car. / 当前公开来源无符合输入预算的车辆。</p>}
 <h2>Before trusting an advertised price / 看报价前先确认</h2><p>Ontario dealer ads generally must include fees the dealer intends to charge, except HST and licensing; unfit/as-is vehicles have additional disclosure rules. Request a written breakdown and check certification status. A low advertised price does not prove good condition or good value.</p><p><a href="https://www.omvic.ca/buying/your-rights/all-in-price-advertising/">OMVIC: all-in price advertising</a> · <a href="/guides/ontario-car-price">Read the worked example / 阅读具体示例</a> · <a href="/compare">Compare your own public links / 比较你找到的车</a></p></>;
}
