import {base,title,vehicleUrl,type Vehicle} from './model';
import {driveCode} from './drivetrain';
export function jsonFeed(v:Vehicle[]){return {version:'1.0',publisher_name:'Warren Vehicle Finder',independent_service:true,source_dealer_name:'Ultimate Motors',generated_at:new Date().toISOString(),vehicles:v.filter(x=>x.availability==='available').map(x=>({...x,vehicle_url:vehicleUrl(x)}))};}
export function csvFeed(v:Vehicle[]){const fields=['stock_number','vin','year','make','model','trim','price_cad','mileage_km','drivetrain','availability','vehicle_url','image_url','dealer_name','region','updated_at'];const escape=(x:unknown)=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';return [fields.join(','),...v.filter(x=>x.availability==='available').map(x=>fields.map(k=>escape(k==='vehicle_url'?vehicleUrl(x):k==='image_url'?x.primary_image:x[k as keyof Vehicle])).join(','))].join('\r\n');}
export function structuredData(v:Vehicle){const s:any={'@context':'https://schema.org','@type':['Car','Product'],name:title(v),url:v.source_vehicle_url,seller:undefined};const fields:any={sku:v.stock_number,vehicleIdentificationNumber:v.vin,brand:v.make?{'@type':'Brand',name:v.make}:null,model:v.model,vehicleModelDate:v.year?.toString(),vehicleTransmission:v.transmission,color:v.exterior_color,image:v.image_urls.length?v.image_urls:null,mileageFromOdometer:v.mileage_km===null?null:{'@type':'QuantitativeValue',value:v.mileage_km,unitCode:'KMT'}};for(const [k,x]of Object.entries(fields))if(x!==null&&x!==undefined)s[k]=x;
 const drives:Record<string,string>={awd:'AllWheelDriveConfiguration','4wd':'FourWheelDriveConfiguration',fwd:'FrontWheelDriveConfiguration',rwd:'RearWheelDriveConfiguration'};const d=drives[driveCode(v.drivetrain)||''];if(d)s.driveWheelConfiguration='https://schema.org/'+d;
 if(v.price_cad!==null&&['available','sold','unavailable'].includes(v.availability))s.offers={'@type':'Offer',price:v.price_cad,priceCurrency:'CAD',availability:'https://schema.org/'+(v.availability==='available'?'InStock':v.availability==='sold'?'SoldOut':'OutOfStock'),url:v.source_vehicle_url,seller:{'@type':'AutoDealer',name:v.dealer_name}};return s;}
export function sitemapEntries(v:Vehicle[]){return [{url:base(),lastModified:undefined},{url:base()+'/inventory',lastModified:undefined},...v.filter(x=>x.availability==='available').map(x=>({url:vehicleUrl(x),lastModified:x.updated_at}))];}

export function serializeJsonLd(value:unknown){return JSON.stringify(value).replace(/</g,'\\u003c');}
