import {validationToken} from '../lib/security';
import {writeFileSync,mkdirSync} from 'node:fs';import * as cheerio from 'cheerio';
import {title,money,mileage,type Vehicle} from '../lib/model';
const base=process.env.TEST_BASE_URL||'http://localhost:3000';const results:{test:string;status:string;detail:string}[]=[];
async function run(name:string,fn:()=>Promise<string>){try{results.push({test:name,status:'PASS',detail:await fn()});}catch(e){results.push({test:name,status:'FAIL',detail:String(e)});}}
const get=async(path:string)=>{const r=await fetch(base+path,{headers:{'User-Agent':'OAI-SearchBot'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(path+' HTTP '+r.status);return r;};
const body=await (await get('/api/vehicles')).json();const inventory=body.vehicles as Vehicle[];
await run('A — Source ingestion',async()=>{if(inventory.length<10)throw new Error('Requires ≥10 verified available source vehicles; found '+inventory.length);for(const v of inventory)console.log(JSON.stringify({stock:v.stock_number,year:v.year,make:v.make,model:v.model,price:v.price_cad,mileage:v.mileage_km,source_url:v.source_vehicle_url}));return inventory.length+' source vehicles';});
await run('B — Crawler initial HTML',async()=>{if(!inventory.length)throw new Error('BLOCKED: no real source vehicles');for(const v of inventory){const html=await(await get('/v/'+encodeURIComponent(v.id))).text();const $=cheerio.load(html);$('script').remove();const text=$('body').text();for(const expected of [title(v),money(v.price_cad),mileage(v.mileage_km),v.stock_number||'Not provided',v.vin||'Not provided',v.availability,'Ultimate Motors'])if(!text.includes(expected))throw new Error('Missing server-rendered fact: '+expected);}return inventory.length+' vehicle pages contain initial HTML facts';});
await run('C — Structured data',async()=>{if(!inventory.length)throw new Error('BLOCKED: no real source vehicles');for(const v of inventory){const $=cheerio.load(await(await get('/v/'+encodeURIComponent(v.id))).text());const data=JSON.parse($('script[type="application/ld+json"]').text());if(!data['@type'].includes('Car')||data.name!==title(v))throw new Error('Invalid vehicle JSON-LD');}return 'All imported pages parse';});
await run('D — Feed/API',async()=>{const feed=await(await get('/feed/inventory.json')).json();const csv=await(await get('/feed/inventory.csv')).text();if(feed.vehicles.length!==inventory.length||!csv.startsWith('stock_number,vin,year'))throw new Error('Feed mismatch');for(const v of inventory){const one=await(await get('/api/vehicles/'+encodeURIComponent(v.stock_number||v.id))).json();if(one.id!==v.id)throw new Error('Stock API mismatch');}return 'JSON, CSV and API agree; '+inventory.length+' vehicles (empty is not ingestion validation)';});
await run('E — Search',async()=>{if(!inventory.length)throw new Error('BLOCKED: no real source vehicles');for(const q of ['2022 rav4','rav4 under 35000','awd suv','honda under 30000']){const r=await(await get('/api/vehicles?q='+encodeURIComponent(q))).json();if(!r.results.length||r.results.some((v:Vehicle)=>!inventory.find(x=>x.id===v.id)))throw new Error('Search fabricated or omitted actual inventory');}return 'Four searches return actual imported vehicles; closest results labeled';});
await run('F — Anonymous inquiry',async()=>{if(!inventory.length)throw new Error('BLOCKED: no real source vehicles');const r=await fetch(base+'/api/inquiries',{method:'POST',headers:{origin:base,'Content-Type':'application/json','x-validation-token':validationToken()},body:JSON.stringify({vehicle_id:inventory[0].id,source:'chatgpt',question:'Has this vehicle been in an accident?'})});const d=await r.json();if(r.status!==201||!d.inquiry_id)throw new Error(JSON.stringify(d));return 'Anonymous inquiry created: '+d.inquiry_id;});
await run('Robots/sitemap',async()=>{const robots=await(await get('/robots.txt')).text();for(const agent of ['Googlebot','Bingbot','OAI-SearchBot'])if(!robots.includes(agent))throw new Error('Missing agent '+agent);const xml=await(await get('/sitemap.xml')).text();for(const v of inventory)if(!xml.includes('/v/'+v.id))throw new Error('Missing available URL');return 'Public crawl directives and dynamic sitemap respond';});
console.table(results);mkdirSync('reports',{recursive:true});writeFileSync('reports/acceptance.json',JSON.stringify({timestamp:new Date().toISOString(),base,source_vehicles:inventory.length,results},null,2)+'\n');if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
