import {customerDB,closeCustomerDB} from '../lib/customer-store';
import {validationToken} from '../lib/security';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';import {randomUUID} from 'node:crypto';import * as cheerio from 'cheerio';
const base=process.env.TEST_BASE_URL||'http://localhost:3000';const checks:{name:string;status:string;detail?:string}[]=[];
async function check(name:string,fn:()=>Promise<void>){try{await fn();checks.push({name,status:'PASS'});}catch(e){checks.push({name,status:'FAIL',detail:String(e)});}}
const json=(path:string,body:any,headers:Record<string,string>={})=>fetch(base+path,{method:'POST',headers:{origin:base,'Content-Type':'application/json','x-validation-token':validationToken(),...headers},body:JSON.stringify(body)});
const data=await(await fetch(base+'/api/vehicles')).json();const items=data.vehicles;assert.ok(items.length>=10,'Integration requires real imported inventory');const v=items[0];
await check('Googlebot, Bingbot and OAI-SearchBot see server-rendered vehicle facts',async()=>{for(const ua of ['Googlebot','Bingbot','OAI-SearchBot']){const r=await fetch(base+'/v/'+v.id,{headers:{'User-Agent':ua}});assert.equal(r.status,200);const $=cheerio.load(await r.text());assert.ok($('h1').text().includes(v.make));assert.ok($('body').text().includes(v.vin));assert.ok($('body').text().includes(v.stock_number));assert.equal(JSON.parse($('script[type="application/ld+json"]').text()).offers.price,v.price_cad);assert.ok($('link[rel="canonical"]').attr('href')?.endsWith('/v/'+v.id));assert.ok($('meta[property="og:title"]').attr('content'));assert.ok($('meta[name="twitter:card"]').attr('content'));assert.ok($('header').text().includes('Warren Vehicle Finder'));assert.ok($('footer').text().includes('not the listing dealer'));assert.equal(JSON.parse($('script[type="application/ld+json"]').text()).offers.url,v.source_vehicle_url);}});
await check('Vehicle and inquiry values are persisted in the configured customer database',async()=>{const d=customerDB;const marker='Integration validation '+randomUUID();const r=await json('/api/inquiries',{vehicle_id:v.id,source:'chatgpt',question:marker});assert.equal(r.status,201);const out=await r.json();const row=await d.prepare('SELECT * FROM inquiries WHERE inquiry_id=?').get(out.inquiry_id);assert.equal(row?.question,marker);assert.equal(row?.vehicle_id,v.id);assert.equal(row?.source,'chatgpt');assert.equal(row?.contact_value,null);assert.ok(row?.created_at);assert.ok(row?.session_id);});
await check('Cross-origin inquiry and tracking submissions are refused',async()=>{assert.equal((await json('/api/inquiries',{question:'test'},{origin:'https://untrusted.example'})).status,403);assert.equal((await json('/api/track',{url:base},{origin:'https://untrusted.example'})).status,403);});
await check('Unknown vehicle and invalid consent are rejected',async()=>{assert.equal((await json('/api/inquiries',{vehicle_id:'nonexistent',question:'test'})).status,400);assert.equal((await json('/api/inquiries',{vehicle_id:v.id,question:'test',contact_value:'test@example.com',consent:false})).status,400);});
await check('Tracking preserves first source across internal landing changes',async()=>{const first=await json('/api/track',{url:base+'/v/'+v.id+'?utm_source=google&utm_campaign=integration',referrer:''});assert.equal(first.status,204);const cookie=first.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');const second=await json('/api/track',{url:base+'/ask?vehicle='+v.stock_number,referrer:base+'/v/'+v.id},{cookie});assert.equal(second.status,204);const d=customerDB;const session=cookie.match(/um_session=([^;]+)/)?.[1];const rows=await d.prepare('SELECT * FROM visits WHERE session_id=? ORDER BY id').all(session!);assert.equal(rows.length,2);assert.equal(rows[0].first_source,'google');assert.equal(rows[1].current_source,'google');assert.equal(rows[0].vehicle_id,v.id);assert.equal(rows[0].landing_page,'/v/'+v.id);});
await check('Public feeds omit unavailable inventory and include stable URLs',async()=>{const f=await fetch(base+'/feed/inventory.json');assert.match(f.headers.get('cache-control')||'',/max-age=60/);const j=await f.json();assert.equal(j.vehicles.length,items.length);assert.ok(j.vehicles.every((x:any)=>x.availability==='available'&&x.vehicle_url.endsWith('/v/'+x.id)));const csv=await(await fetch(base+'/feed/inventory.csv')).text();assert.equal(csv.split('\r\n').length,items.length+1);});
await check('Source parameter works on ask; no account or compulsory contact',async()=>{const r=await fetch(base+'/ask?vehicle='+v.stock_number+'&source=chatgpt');assert.equal(r.status,200);const $=cheerio.load(await r.text());assert.ok($('h1').text().includes('Ask about this vehicle'));assert.equal($('input[name="contact_value"]').attr('required'),undefined);});
await check('No exact match is clearly labeled in initial search HTML',async()=>{const r=await fetch(base+'/inventory?q='+encodeURIComponent('nonexistentmodel under 1'));const $=cheerio.load(await r.text());assert.ok($('body').text().includes('No exact match found'));assert.ok($('a[href^="/v/"]').length>0);});
await check('Admin requires signed authentication; dashboard displays real counts',async()=>{assert.equal((await fetch(base+'/api/admin/sync',{method:'POST',headers:{origin:base}})).status,403);const page=await(await fetch(base+'/admin')).text();assert.ok(page.includes('Admin password'));assert.ok(!page.includes('Inventory dashboard'));const password=process.env.ADMIN_PASSWORD||readFileSync('.env.local','utf8').match(/^ADMIN_PASSWORD=(.+)$/m)?.[1];assert.ok(password);const response=await fetch(base+'/api/admin/login',{method:'POST',headers:{origin:base,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({password}),redirect:'manual'});assert.equal(response.status,303);assert.equal(new URL(response.headers.get('location')!).origin,base);const cookie=response.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');assert.ok(cookie);const dashboard=await fetch(base+'/admin',{headers:{cookie}});const html=await dashboard.text();assert.ok(html.includes('Inventory dashboard'));assert.ok(html.includes('Traffic sources'));assert.ok(html.includes('Most queried vehicles'));assert.ok(html.includes('Manage a lead'));const adminTest=await fetch(base+'/api/admin/test-inquiry',{method:'POST',headers:{origin:base,cookie,accept:'application/json'}});assert.equal(adminTest.status,201);const adminTestBody=await adminTest.json();assert.equal(adminTestBody.is_test,true);const storedTest=await customerDB.prepare('SELECT is_test FROM inquiries WHERE inquiry_id=?').get(adminTestBody.inquiry_id);assert.equal(storedTest?.is_test,1);assert.equal((await fetch(base+'/api/admin/lead',{method:'POST',headers:{origin:base,cookie,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({inquiry_id:adminTestBody.inquiry_id,status:'delete'}),redirect:'manual'})).status,303);const testLead=await(await json('/api/inquiries',{question:'Integration validation lead workflow',contact_method:'Email',contact_value:'test@example.com',consent:true})).json();const update=(status:string,origin=base)=>fetch(base+'/api/admin/lead',{method:'POST',headers:{origin,cookie,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({inquiry_id:testLead.inquiry_id,status}),redirect:'manual'});assert.equal((await update('contacted')).status,303);assert.equal((await update('qualified')).status,400);assert.equal((await update('closed','https://untrusted.example')).status,403);assert.equal((await update('delete')).status,303);assert.equal((await update('contacted')).status,404);assert.equal((await fetch(base+'/api/admin/sync',{method:'POST',headers:{origin:'https://untrusted.example',cookie}})).status,403);const logout=await fetch(base+'/api/admin/logout',{method:'POST',headers:{origin:base,cookie},redirect:'manual'});assert.equal(logout.status,303);});
await check('Admin login throttles repeated failures',async()=>{let last=0;for(let i=0;i<6;i++){last=(await fetch(base+'/api/admin/login',{method:'POST',headers:{origin:base,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({password:'invalid-test-password'})})).status;}assert.equal(last,429);});
console.table(checks);mkdirSync('reports',{recursive:true});writeFileSync('reports/integration.json',JSON.stringify({timestamp:new Date().toISOString(),inventory_count:items.length,checks},null,2)+'\n');if(checks.some(c=>c.status==='FAIL'))process.exitCode=1;

await closeCustomerDB();
